### ISSUE TITLE
Hardware Picture (DSC-49)

### ISSUE THREAD

**Issue by piogor** [tango-controls/dsc#2]
Provide possibility to upload and show a picture (for example hardware) for a device server.
This task is related to https://3controls.atlassian.net/projects/DSC/issues/DSC-49.

**Comment by piogor** [comment]
The feature is implemented. Preview is available on the test server: https://dsc-test.modelowanie.pl/resources/dsc/ds/1572/

**Comment by andygotz** [comment]
Looks good! Would it be possible to display images like the one I have attached? What are the limits on the picture size and resolution? Do they get resized as thumbnails automatically?

![varianmultigauge](https://user-images.githubusercontent.com/1167099/29604177-f6069962-87e6-11e7-927c-7ac4dedabd27.jpg)

**Comment by piogor** [comment]
Yes, you may upload the image. If you select 'Edit', there is a field called Picture.
 
 It will be scaled to 100 x 100 in the view. However, I am not checking resolution on upload. File size is limited to 1MB.  I think I need to change the behaviour of the scaling - changing "width" css property to "max-width" to allow for nicer look if case of rectangular pictures.
